version: "3"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - /frontend/.next
    networks:
      - internal

  adonis_app:
    restart: always
    build:
      context: ./trajeto-algoritmos-api
    ports:
      - "2053:2053"
    volumes:
      - ./trajeto-algoritmos-api:/trajeto-algoritmos-api
      # Uncomment the below line if you're developing on MacOS
      #- /home/node/app/node_modules
      - ./trajeto-algoritmos-api/node_modules:/trajeto-algoritmos-api/node_modules
    networks:
      - internal
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: usuario
      MYSQL_PASSWORD: NQBtIBVdeLyS
      MYSQL_DATABASE: projeto_algoritmos
      MYSQL_ROOT_PASSWORD: k0Jn,bb99*
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

  server:
    container_name: judge0
    image: judge0/judge0:1.13.0
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    restart: always
    networks:
      - internal

  workers:
    image: judge0/judge0:1.13.0
    command: ["./scripts/workers"]
    volumes:
      - ./judge0/judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always
    networks:
      - internal

  db:
    image: postgres:13.0
    env_file: ./judge0/judge0.conf
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    restart: always
    networks:
      - internal

  redis:
    image: redis:6.0
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: ./judge0/judge0.conf
    volumes:
      - redis-data:/data
    restart: always
    networks:
      - internal

volumes:
  mysql-data:
  postgres-data:
  redis-data:

networks:
  internal:
    driver: bridge
